default_language_version:
  python: python3.11

repos:
  - repo: local
    hooks:
      - id: mypy
        name: mypy (poetry)
        entry: poetry run mypy
        language: system
        types: [python]
        pass_filenames: true
        args:
          - --config-file=pyproject.toml
          - --no-incremental
      - id: black
        name: black (poetry)
        entry: poetry run black
        language: system
        types: [python]
        pass_filenames: true
        args: []
      - id: pytest
        name: pytest (poetry)
        entry: poetry run pytest -q
        language: system
        types: [python]
        pass_filenames: false
